language: ruby
cache: bundler
bundler_args: "--without production"
rvm:
- 2.4.1
services:
- postgresql
- redis

before_script: sudo redis-server /etc/redis/redis.conf --port 6380 --requirepass 'secret'

script:
- bin/rake db:reset RAILS_ENV=test
- bin/rake
