# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bc16d660b25d23cdee8b65cea5cd7d0c35616ad88f69160bc9015af2d804ade6edc5f1bbe1cbe99166bedc0f1ae953541670b4c13a86b72a6fc51435100f8bc6

test:
  secret_key_base: 02a11089e0069edf9d8ba41010945eaf7fdf63e1971f536c2ff6e67b15b8afdc139adc62f73a2167f2366ead4e8b5851d048f036cc471623e66161fb9ab16c06

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
